apiVersion: v1
kind: Namespace
metadata:
  name: knative-serving
---
apiVersion: operator.knative.dev/v1alpha1
kind: KnativeServing
metadata:
  name: knative-serving
  namespace: knative-serving
spec:
  config:
    defaults:
      revision-timeout-seconds: "300"  # 5 minutes
    autoscaler:
      stable-window: "60s"
    deployment:
      registriesSkippingTagResolving: "ko.local,dev.local"
    logging:
      loglevel.controller: "debug"
    network:
      istio.sidecar.includeOutboundIPRanges: "172.30.0.0/16,172.20.0.0/16,10.10.10.0/24"
     # domainTemplate: "{{=<% %>=}}{{.Name}}-{{.Namespace}}.{{.Domain}}"
    domain:
      vincent-development-5290c8c8e5797924dc1ad5d1b85b37c0-0000.us-east.containers.appdomain.cloud: ""

